print('Vamos analizar uma entrada!')
coisa = input('Digíte alguma coisa: ')
print('O tipo primitivo desse valor é: ', type(coisa))
print('Só tem espaços? ', coisa.isspace())
print('É numérico? ', coisa.isnumeric())
print('É alfabético? ', coisa.isalpha())
print('É alfanumérico? ', coisa.isalnum())
print('É tudo maiúsculo? ', coisa.isupper())
print('É tudo minúsculo? ', coisa.islower())
print('Esta capitalizado? ', coisa.istitle())
